[woodpecker]
#/etc/portage/repos.conf/woodpecker.conf
location = /var/db/repos/woodpecker
sync-type = git
sync-uri = https://github.com/Necrohol/woodpecker.git
priority = 50
auto-sync = yes

# Direct injection into Portage
#curl -s https://githubusercontent.com \
  #  -o /etc/portage/repos.conf/woodpecker.conf && \
#emaint sync -r woodpecker

